import openpyxl as op
import os
import pandas as pd

REPORT_HEADER = 'Report automatically generated by'

def delete_top_rows(workbook_name, num_rows=3, condition=REPORT_HEADER):
    """
    This function uses openpyxl to remove the specified number of rows 
    from the top of an Excel file if a given condition is met.
    """
    book = op.load_workbook(workbook_name)
    sheet = book.worksheets[0]

    if condition in sheet['A2'].value:
        sheet.delete_rows(1, num_rows)
        book.save(workbook_name)
    else:
        return None

def save_csv_as_xlsx(csv_location):
    """
    Saves a CSV file as an Excel file to display UTF-8 characters 
    correctly on macOS, as Excel displays UTF-8 characters in CSV files 
    incorrectly.
    """
    if not csv_location.lower().endswith('.csv'):
        raise ValueError("Input file must have a .csv extension")

    df = pd.read_csv(csv_location, encoding='utf-8', low_memory=False)
    df = df.fillna('')

    for column in df:
        df[column] = df[column].str.strip()

    new_workbook_name = os.path.splitext(csv_location)[0] + '.xlsx'
    df.to_excel(new_workbook_name, index=False)
